# Generated by Django 5.1.3 on 2025-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_last_maintenance_date_itasset_ups_battery_replacement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='owner',
            field=models.CharField(choices=[('radioshack', 'RadioShack'), ('computer_shop', 'Computer Shop'), ('mobile_shop', 'Mobile Shop'), ('compu_me', 'Compu Me'), ('smart_home', 'Smart Home'), ('vodafone', 'vodafone')], default='radioshack', max_length=20),
        ),
    ]
