# Generated by Django 5.2.1 on 2025-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='Enter employee ID (e.g., EMP001 or ABC123)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ownercompany',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
