# Generated by Django 5.2.1 on 2025-05-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_itreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITReport',
        ),
    ]
