# Generated by Django 5.2.1 on 2025-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_update_owner_companies'),
        ('inventory', '0039_message'),
    ]

    operations = [
    ]
