# Generated by Django 5.2.1 on 2025-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assethistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Asset Histories'},
        ),
        migrations.AlterModelOptions(
            name='itasset',
            options={},
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'In Maintenance'), ('return', 'Returned'), ('disposed', 'Disposed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'In Maintenance'), ('return', 'Returned'), ('disposed', 'Disposed')], default='available', max_length=20),
        ),
    ]
