# Generated by Django 5.2.1 on 2025-05-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_assethistory_options_alter_itasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inventory.employee'),
        ),
    ]
