# Generated by Django 5.2.1 on 2025-05-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_remove_message_updated_at_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_new_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itasset'),
        ),
        migrations.AlterField(
            model_name='message',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.employee'),
        ),
    ]
