# Generated by Django 5.2.1 on 2025-05-25 10:20

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
    ]
