# Generated by Django 5.2.1 on 2025-05-25 12:08

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='date',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(default=inventory.models.get_cairo_time),
        ),
    ]
