# Generated by Django 5.2.2 on 2025-06-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Ticket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='parent_message',
            new_name='parent_ticket',
        ),
    ]
