# Generated by Django 5.2.2 on 2025-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_alter_employee_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
