# Generated by Django 5.2.2 on 2025-06-16 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_employee_position_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position_text',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
