# Generated by Django 5.2.2 on 2025-06-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_convert_position_to_char'),
        ('inventory', '0060_remove_employee_position_text_and_more'),
    ]

    operations = [
    ]
